### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by lumia1998** [initialencounter/koishi-plugin-open-vits#10]
提示报错,插件提示没有readme这个文件,插件目录录是README,修改小写重启后可以启动
但是现在仍然报错
![image](https://github.com/initialencounter/koishi-plugin-open-vits/assets/63107956/4bd3844d-c6c9-4e07-8a99-496dbe9b0e60)

**Comment by initialencounter** [comment]
这是windows系统不区分大小写导致的

**Comment by initialencounter** [comment]
> 但是现在仍然报错

这是另一个报错吗？

**Comment by lumia1998** [comment]
> > 但是现在仍然报错
> 
> 这是另一个报错吗？

是的,我第一个报错大小写的是docker的,修改小写后解决,windows的新实例没问题.docker这个故障我还在找原因,目前从依赖卸载重装无效,以后尝试下双清.
再就是希望gsv那个选项可以多一个随机一个参考音频生成,刚刚测试,就默认效果,gsv的没参考音频效果和vits没区别,以后的fs也要有参考音频.

**Comment by lumia1998** [comment]
双亲

> > 但是现在仍然报错
> 
> 这是另一个报错吗？

双清后解决
