### ISSUE TITLE
`say -l <lang>`不起作用

### ISSUE THREAD

**Issue by kaoet** [initialencounter/koishi-plugin-open-vits#11]
如果lang设置正确，则应该中日语为不同读法：
* https://artrajz-vits-simple-api.hf.space/voice/vits?text=主人&id=160&lang=zh
* https://artrajz-vits-simple-api.hf.space/voice/vits?text=主人&id=160&lang=ja

但实际中`say -l ja 主人`和`say -l zh 主人`都为中文读法。`-l ja`参数完全没有传递到实际的VITS API中。

**Comment by initialencounter** [comment]
感谢反馈，已修复 v2.0.4

**Comment by initialencounter** [comment]
say的时候 jp 改成 ja

**Comment by kaoet** [comment]
实测此问题并没有得到修复。

可以看到传给`baseSay()`的只有`speaker id`和输入文本，而`options.lang`则没有传递下去。
https://github.com/initialencounter/koishi-plugin-open-vits/blob/main/src/index.ts#L168-L169

因此最终URL自然没有受到`options.lang`的影响。

**Comment by initialencounter** [comment]
已修复 v2.0.5
