### ISSUE TITLE
可以添加设置模型类型的功能吗

### ISSUE THREAD

**Issue by chara006688** [initialencounter/koishi-plugin-open-vits#7]
这是我在网页端获取的可以正常使用的情况
![图片](https://github.com/initialencounter/koishi-plugin-open-vits/assets/99468176/67f7530d-c2a2-400b-b6df-b60e06623e62)
![图片](https://github.com/initialencounter/koishi-plugin-open-vits/assets/99468176/add5099d-c9cc-4362-ba22-3cf01d7bf2a8)
这是我在插件内获取的
![图片](https://github.com/initialencounter/koishi-plugin-open-vits/assets/99468176/d5bcf0e3-49d7-4809-8732-9b655467c933)
![图片](https://github.com/initialencounter/koishi-plugin-open-vits/assets/99468176/40ab27b6-d69a-479a-947c-7f1ccfb59408)

**Comment by initialencounter** [comment]
这似乎是bert-vits2的接口，有时间会做

**Comment by chara006688** [comment]
> 这似乎是bert-vits2的接口，有时间会做

好像现在vits-simple-api的GET是带模型类型的

**Comment by initialencounter** [comment]
> > 这似乎是bert-vits2的接口，有时间会做
> 
> 好像现在vits-simple-api的GET是带模型类型的

v2.0.0做好了，去更新吧
